//
// Created by Drumm on 2024-04-06.
//

#ifndef HUFFMAN_ENCODER_UNITTESTS_H
#define HUFFMAN_ENCODER_UNITTESTS_H
int PRIORITY_QUEUE_PRINT_TEST();
int LOOKUP_TESTS();
#endif //HUFFMAN_ENCODER_UNITTESTS_H
